apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-api-deployment
  namespace: solid-api-2024
  labels:
    app: node-api
    # pod-security.kubernetes.io/enforce: restricted (Placeholder: for clarity, this should be applied on namespace once codebase is production ready)
spec:
  replicas: 6
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  selector:
    matchLabels:
      app: node-api
  template:
    metadata:
      labels:
        app: node-api
    spec:
      imagePullSecrets:
        - name: hcs522-ghcr-secret
      containers:
        - name: node-api
          image: ghcr.io/theflyingpig83/solid-api/node-api:<IMAGE_TAG>
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
            runAsGroup: 1001
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 5050
          resources:
            requests:
              memory: "250Mi"   
              cpu: "200m"      
            limits:
              memory: "300Mi"  
              cpu: "400m"     
          env:
          - name: DB_HOST
            value: "postgres.solid-api-2024.svc.cluster.local"
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: postgres-credentials
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-credentials
                key: password
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: postgres-credentials
                key: database
          - name: DB_PORT
            value: "5432"
---
apiVersion: v1
kind: Service
metadata:
  name: node-api-service
  namespace: solid-api-2024
spec:
  selector:
    app: node-api
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 5050
  type: LoadBalancer
